package com.aionemu.gameserver.model;

public enum TaskId
{
	DECAY,
	RESPAWN,
	PRISON,
	PROTECTION_ACTIVE,
	DROWN,
	DESPAWN,
	QUEST_TIMER,
	QUEST_FOLLOW,
	PLAYER_UPDATE,
	INVENTORY_UPDATE,
	GAG,
	ITEM_USE,
	ACTION_ITEM_NPC,
	EXPRESS_MAIL_USE,
	SKILL_USE,
	GATHERABLE,
	PET_UPDATE,
	SUMMON_FOLLOW,
	MATERIAL_ACTION,
	SIEL_UPDATE,
	EVENT_WINDOW_UPDATE,
	REPOSE_ENERGY_TASK,
	BLACK_CLOUD_CHECK
}